# Generated by Django 4.1.5 on 2023-02-08 09:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название органа')),
                ('element', models.CharField(default='', max_length=255, verbose_name='Химиялық элемент')),
                ('slug', models.SlugField(max_length=255, verbose_name='Ключ органа')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Орган',
                'verbose_name_plural': 'Органы',
            },
        ),
    ]
